### ISSUE TITLE
Bu yerlarda ham h2 ni ishlatsak yaxshi bo'lmaydimi. Bizga ustozimiz ma'nosiga qarab darajasini belgilanglar deb aytardi. Shunga menimcha h4 va h5 qilinsa ma'no jihatidan juda kichkina bo'lib ketsa kerak

### ISSUE THREAD

**Issue by mashhurbek2005** [nizamoff/tingla-site#2]
![image](https://user-images.githubusercontent.com/105698306/187081042-ecfc1a06-40c1-4826-aa21-02660a49b6df.png)

**Comment by nizamoff** [comment]
SEO va Google botlari qanday ishlashidan xabaringiz bo'lsa kerak albatta. Ular siz bergan stillardan ko'ra sarlavha tag larini to'g'ri ketma-ketlikda joylashtirganingizga e'tibor berishadi.

**Comment by nizamoff** [comment]
> SEO va Google botlari qanday ishlashidan xabaringiz bo'lsa kerak albatta. Ular siz bergan stillardan ko'ra sarlavha tag larini to'g'ri ketma-ketlikda joylashtirganingizga e'tibor berishadi.
